import { ApplicationForm } from './form.model';

export const formConfiguration: ApplicationForm = {
  personalInformation: [
    {
      fieldName: 'firstName',
      label: 'First Name',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'middleName',
      label: 'Middle Name',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'lastName',
      label: 'Last Name',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'dateOfBirth',
      label: 'Date of Birth',
      type: 'date',
      required: true,
    },
    {
      fieldName: 'age',
      label: 'Age',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'country',
      label: 'Country',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'city',
      label: 'City',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'home',
      label: 'Home',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'workAddress',
      label: 'Work Address',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'additionalAddress',
      label: 'Additional Address',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'countryOfBirth',
      label: 'Country of Birth',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'cityOfBirth',
      label: 'City of Birth',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'postal',
      label: 'Postal',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'pob',
      label: 'POB',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'citizenship',
      label: 'Citizenship',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'relationship',
      label: 'Relationship',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'idNumber',
      label: 'ID Number',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'passportNumber',
      label: 'Passport Number',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'licenceNumber',
      label: 'Licence Number',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'licencePlate',
      label: 'Licence Plate',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'motherName',
      label: 'Mother Name',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'fatherName',
      label: 'Father Name',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'partnerName',
      label: 'Partner Name',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'siblingsNames',
      label: 'siblingsNames',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'childrenNames',
      label: 'Children Names',
      type: 'string',
      required: true,
    },
  ],
  contactInformation: [
    {
      fieldName: 'landlinePhone',
      label: 'Landline Phone',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'mobilePhone',
      label: 'Mobile Phone',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'emailAddress',
      label: 'Email Address',
      type: 'string',
      required: false,
    },
    {
      fieldName: 'facebookAccount',
      label: 'Facebook Account',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'facebookId',
      label: 'Facebook ID',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'linkedinAccount',
      label: 'Linkedin Account',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'instagramAccount',
      label: 'Instagram Account',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'twitterAccount',
      label: 'Twitter Account',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'vkNumber',
      label: 'VK Number',
      type: 'string',
      required: true,
    },
  ],
  legalInformation: [
    {
      fieldName: 'caseName',
      label: 'Case Name',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'caseNumber',
      label: 'Case Number',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'judgeName',
      label: 'Judge Name',
      type: 'string',
      required: true,
    },
  ],
  businessInformation: [
    {
      fieldName: 'companyName',
      label: 'Company Name',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'registrationNumber',
      label: 'Registration Number',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'registrationDirector',
      label: 'Reg. Director',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'businessAddress',
      label: 'Business Address',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'businessEmail',
      label: 'Business Email',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'businessPhoneNumber',
      label: 'Business Phone Number',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'certifiedEmployer',
      label: 'Certified Employer',
      type: 'string',
      required: true,
    },
  ],
  professionalInformation: [
    {
      fieldName: 'employment',
      label: 'employment',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'education',
      label: 'Education',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'jobTitle',
      label: 'Job Title',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'bankAccountNumber',
      label: 'Bank Account Number',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'branchNumber',
      label: 'Branch Number',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'bankNumber',
      label: 'Bank Number',
      type: 'string',
      required: true,
    },
    {
      fieldName: 'ipAddress',
      label: 'IP Address',
      type: 'string',
      required: true,
    },
  ],
  additionalInformation: [{
    fieldName: 'additionalInformation',
    label: 'Additional Information',
    type: 'string',
    required: false,
  }],
  files: [{
    fieldName: 'files',
    label: 'Additional Information',
    type: 'string',
    required: false,
  }]
};
